[package]
name = "Task3"
version = "0.0.1"
authors = ["Oleksandr Kovalov <oleksandr.kovalov.work@gmail.com>"]

edition = "2024"
rust-version = "1.95"

categories = ["security"]

readme = "../README.md"
repository = "https://github.com/xairaven/ProgammaTestTasks"

[lints]
workspace = true

[dependencies]
chrono = "0.4.44"
crossbeam = "0.8.4"
clap = { version = "4.6.0", features = ["derive"] }
fern = "0.7.1"
log = "0.4.29"
thiserror = "2.0.18"
