[package]
name = "Task2"
version = "0.0.1"
authors = ["Oleksandr Kovalov <oleksandr.kovalov.work@gmail.com>"]

edition = "2024"
rust-version = "1.95"

categories = ["security"]

readme = "../README.md"
repository = "https://github.com/xairaven/ProgammaTestTasks"

[lints]
workspace = true

[dependencies]
thiserror = "2.0.18"
